### PR TITLE
🐋 Update Dockerfile

### PR DESCRIPTION
**Pull request by devarops**
- [ ] ~Evoca mutantes en el _pipeline_ CI/CD~
- [x] Corre una prueba _dummy_ en el _pipeline_ CI/CD
- [x] Evalúa cambio de cobertura en el _pipeline_ CI/CD
- [x] Verifica el formato en el _pipeline_ CI/CD
- [ ] ~Realiza análisis estático en el _pipeline_ CI/CD~
- [x] Agrega _phony_ `linter` a `Makefile`

### CODE REVIEW

**Comment by xwalls** [comment]
Intentare replicar el escenario y agregare un checklist ✌🏽

**Review by xwalls — COMMENTED** [review]
The Dockerfile is looking for "src/Cronfile" file that actually did not exist on this branch, but it is on another one called `feature/loop`.

@devarops
what we can do about this? any ideas?
can we just write the same file here?

**Comment by devarops** [comment]
> can we just write the same file here?

Done.

**Review by xwalls — COMMENTED** [review]
@devarops 
Excelent,
I think that we can give some human reading to the cronfile,
Would this work?
```# Variables de entorno
SHELL=/bin/bash
UUID=0cfab8be-3e7f-41a1-a30c-613d18f4becb
# Cron jobs
0 1 * * *   curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${UUID}/start && \
            source /.vault/.secrets && \
            /workdir/src/inspect_list.sh && \
            curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${UUID}
```
if you agree, let me do the change ;)

**Review by xwalls — COMMENTED** [review]
@devarops 
The cronfile has some format problems

```
shellcheck -x --shell=bash src/*

In src/Cronfile line 5:
0 1 * * *   curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${UUID}/start && \
    ^-- SC2035: Use ./*glob* or -- *glob* so names with dashes won't become options.
      ^-- SC2035: Use ./*glob* or -- *glob* so names with dashes won't become options.
        ^-- SC2035: Use ./*glob* or -- *glob* so names with dashes won't become options.


In src/Cronfile line 6:
            source /.vault/.secrets && \
                   ^--------------^ SC1091: Not following: /.vault/.secrets: openBinaryFile: does not exist (No such file or directory)
```

Considering that cronfiles are little special files.
Do you think it would be good to exclude cronfile from spellcheck?

```
shellcheck -x --shell=bash src/*.sh
```

**Comment by devarops** [comment]
> Considering that cronfiles are little special files, do you think it would be good to exclude Cronfile from SpellCheck?

Yes, I agree.

**Comment by devarops** [comment]
@xwalls GitHub Actions is passing now 😉 
Could you please review this PR again?
Thanks!

**Comment by xwalls** [comment]
> @devarops
> Excelent,
> I think that we can give some human reading to the cronfile,
> Would this work?
> 
> ```
> SHELL=/bin/bash
> UUID=0cfab8be-3e7f-41a1-a30c-613d18f4becb
> # Cron jobs
> 0 1 * * *   curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${UUID}/start && \
>             source /.vault/.secrets && \
>             /workdir/src/inspect_list.sh && \
>             curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${UUID}
> ```
> 
> if you agree, let me do the change ;)

sup @devarops ? maybe was not a good idea?

**Comment by devarops** [comment]
> maybe was not a good idea?

Give a minute to check it out...

**Comment by devarops** [comment]
@xwalls I refactored the Cronefile. I am not sure we can break a line in the Cronefile in the way you suggest.

**Review by xwalls — APPROVED** [review]

**Pull request merged**
